cfg = coder.gpuConfig('lib');
cfg.GpuConfig.SelectCudaDevice = 0;
cfg.GenerateReport = true;
cfg.ReportPotentialDifferences = false;

ARGS = {coder.typeof(single(0),[1024 128],[1 1]), ...
        coder.typeof(single(0)), ...
        coder.typeof(single(0)), ...
        coder.typeof(single(0)), ...
        coder.typeof(single(0))};

codegen -config cfg us_beamform -args ARGS -d ../../cuda_generated/beamform
